<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT53JzdD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT53JzdD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT53JzdD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT53JzdD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT53JzdD\App_KernelDevDebugContainer([
    'container.build_hash' => 'T53JzdD',
    'container.build_id' => '4cfd49cb',
    'container.build_time' => 1588857171,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT53JzdD');
