App:
    resource: App\Controller\AppController
    type: annotation

Homepage:
    resource: App\Controller\HomepageController
    type: annotation

User:
    resource: App\Controller\UserController
    type: annotation

Admin:
    resource: App\Controller\AdminController
    type: annotation

Articles:
    resource: App\Controller\ArticlesController
    type: annotation

# controllers:
#     resource: ../../src/Controller/
#     type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
